[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = ["server"] }
bincode = { workspace = true }
bevy = { workspace = true }
bevy_renet = { workspace = true }
serde = { workspace = true }

[features]
"debug" = []